### ISSUE TITLE
Huge delay after changing chunk

### ISSUE THREAD

**Issue by Zuupo** [Wxrlds/Technocratica#12]
I always get a huge delay (updates and block interactions) when i walk into another chunk. I play on a server and never had this problem b4 ... how could i fix this, thx.

**Comment by Wxrlds** [comment]
Since you aren't in Singleplayer, I can imagine some other players might be generating new chunks. Does this problem appear for other players to? Do you have issues when playing alone on the server? What is your servers TPS (Check with "/forge tps"). Is your ping high on the server?
There could be so many causes for this problem and I honstly don't think I can change something from a packdev perspective.

**Comment by Zuupo** [comment]
It seems independent from everything, i was just hoping someone had this issue before. :/

**Comment by Wxrlds** [comment]
Closing this as I don't think I can fix this
